<script lang="ts">
 import FileCode from '@lucide/svelte/icons/file-code';
import Folder from '@lucide/svelte/icons/folder';
 import ChevronRight from '@lucide/svelte/icons/chevron-right';
 let { files, folders=[], pending={}, selected, cut='', onselect, oncontext, ondrag=()=>{}, ondrop=()=>{}, dragEnabled=true }: {files:string[];folders?:string[];pending?:Record<string,string>;selected:string;cut?:string;onselect:(name:string)=>void;oncontext:(path:string,kind:'file'|'folder',x:number,y:number)=>void;ondrag?:(event:DragEvent,path:string,kind:'file'|'folder')=>void;ondrop?:(event:DragEvent,folder:string)=>void;dragEnabled?:boolean}=$props();
 let dropTarget=$state('');
 type Node={name:string;path:string;children:Node[];file:boolean};
 let tree=$derived.by(()=>{const roots:Node[]=[];for(const path of [...folders.map(p=>p+'/'),...files].sort()){let nodes=roots;const parts=path.replace(/\/$/,'').split('/');for(let i=0;i<parts.length;i++){let node=nodes.find(n=>n.name===parts[i]);if(!node){node={name:parts[i],path:parts.slice(0,i+1).join('/'),children:[],file:!path.endsWith('/')&&i===parts.length-1};nodes.push(node);}nodes=node.children;}}return roots;});
</script>
{#snippet branch(nodes:Node[])}
 {#each nodes as node}
  {#if node.file}<button draggable={dragEnabled} ondragstart={e=>ondrag(e,node.path,'file')} class:active={selected===node.path} class:cut={cut===node.path} class:pending-removal={pending[node.path]==='delete'} title={node.path} onclick={()=>onselect(node.path)} oncontextmenu={e=>{e.preventDefault();e.stopPropagation();oncontext(node.path,'file',e.clientX,e.clientY);}} onkeydown={e=>{if(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10')){e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();oncontext(node.path,'file',rect.left+24,rect.bottom);}}}><FileCode size={14}/><span>{node.name}</span>{#if pending[node.path]}<small>{pending[node.path]==='delete'?'Will remove':'Will update'}</small>{/if}</button>
  {:else}<details open><summary draggable={dragEnabled} ondragstart={e=>ondrag(e,node.path,'folder')} ondragover={e=>{if(dragEnabled&&e.dataTransfer?.types.includes('application/x-sovereign-workspace-item')){e.preventDefault();e.stopPropagation();dropTarget=node.path;e.dataTransfer.dropEffect=e.ctrlKey||e.metaKey?'copy':'move';}}} ondragleave={()=>dropTarget=''} ondrop={e=>{dropTarget='';ondrop(e,node.path);}} class:drop-target={dropTarget===node.path} class:pending-removal={pending[node.path]==='rmdir'} tabindex="0" title={node.path} oncontextmenu={e=>{e.preventDefault();e.stopPropagation();oncontext(node.path,'folder',e.clientX,e.clientY);}} onkeydown={e=>{if(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10')){e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();oncontext(node.path,'folder',rect.left+24,rect.bottom);}}}><ChevronRight size={12} class="folder-chevron"/><Folder size={14}/>{node.name}{#if pending[node.path]==='rmdir'}<small>Will remove</small>{/if}</summary><div class="children">{@render branch(node.children)}</div></details>{/if}
 {/each}
{/snippet}
<div class="tree" aria-label="Workspace files">{@render branch(tree)}</div>
<style>.pending-removal span{text-decoration:line-through}.tree small{margin-left:auto;font-size:10px;color:var(--muted-foreground)}.tree{font-size:12px;}button,summary{display:flex;align-items:center;gap:7px;width:100%;padding:6px 8px;cursor:pointer;white-space:nowrap;text-align:left;}button:hover,summary:hover{background:var(--accent);}button.active{background:var(--accent);color:var(--foreground);}button.cut{opacity:.45;}button span{overflow:hidden;text-overflow:ellipsis;}summary{font-weight:500;}.children{padding-left:12px;}summary::-webkit-details-marker{display:none}summary{list-style:none}:global(.folder-chevron){flex-shrink:0;transition:transform .12s}details[open]>summary :global(.folder-chevron){transform:rotate(90deg)}summary.drop-target{background:var(--accent);outline:1px solid var(--wb-focus);outline-offset:-1px}button[draggable=true],summary[draggable=true]{cursor:grab}button[draggable=true]:active,summary[draggable=true]:active{cursor:grabbing}@media(prefers-reduced-motion:reduce){:global(.folder-chevron){transition:none}}</style>
